{% set name = "pyadi-iio" %}
{% set version = "0.0.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/analogdevicesinc/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d5f63001e84e28de1522a62d4666021c4f7af2e6cf6d313bd0b4d1dfee396742

build:
  number: 0
  noarch: python
  # moving test package into adi package to avoid possible global name conflict
  script: mv test adi/ && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - fs
    - paramiko
    - pylibiio
    - numpy
    - python >=3.6

test:
  imports:
    - adi

about:
  home: https://wiki.analog.com/resources/tools-software/linux-software/pyadi-iio
  summary: Interfaces to stream data from ADI hardware
  license: LicenseRef-BSD-Analog-Devices
  license_family: BSD
  license_file: LICENSE
  description: |
    To simplify the use of different devices a python package was created interface
    with the different IIO drivers. The module pyadi-iio, provides device-specific
    APIs built on top of the current libIIO python bindings. These interfaces try to
    match the driver naming as much as possible without the need to understand the
    complexities of libIIO and IIO. In general, if you are familiar with python this
    is a great starting point for using different ADI parts and can even run on some
    ADI development systems as well.
  doc_url: https://analogdevicesinc.github.io/pyadi-iio/
  dev_url: https://github.com/analogdevicesinc/pyadi-iio

extra:
  recipe-maintainers:
    - ryanvolz
